mission:
    resource: "@MissionBundle/Controller/"
    type:     annotation
    prefix:   /
    
_partionneur:
    pattern:  /mission/partionneur
    defaults: { _controller: MissionBundle:Default:partionneur }
    